### PR TITLE
More endpoints, more tests, more things

### PR DESCRIPTION
**Pull request by infinite-monkeys**
Hi,

Now that the project is seeing some activity again, we'd like to contribute the couple years worth of changes we've made (based off of v0.0.5).  I've rebased them against current master in this branch.  I realize some of these may be problematic, as the create/update/delete method signatures have diverged (in order to support generically the service endpoints that require `?advertiser_id` and `?publisher_id`) from the current version.

I've updated the tests in upstream, as well (which I couldn't get to pass in master with our credentials... maybe there is some assumptions made or different behaviors in the API depending on the account type?) Please take a look at the approach and let me know if this is acceptable for merging.  I can definitely split up some of the commits if you want to take the resource/services, but not the tests or other changes.

### CODE REVIEW

**Comment by joshuawscott** [comment]
Thanks for the PR! We'll take a look, trying to see how much impact the API changes will have on our projects that use this.

**Comment by infinite-monkeys** [comment]
@joshuawscott -- Since we've pretty much always used it with the changed signature, it didn't cross my mind to throw that into the UPGRADING.md, but the general gist is:

If before you did `foo_service.create/update/delete(params)` that should work as `foo_service.create/update/delete({}, params)` -- the first hash gets stuck on the end of the URL parameters, the second hash gets passed in the POST body.

**Comment by apurvis** [comment]
👍 to this PR

**Comment by apurvis** [comment]
would be really great also to get a 1.0 release cut and some semantic versioning started.

**Comment by joshuawscott** [comment]
@apurvis @infinite-monkeys should I merge this and the other and release 1.0?

**Comment by joshuawscott** [comment]
@infinite-monkeys I'm getting 17 failures on a potential 1.0 branch with this one and #14 merged in. 

https://gist.github.com/joshuawscott/5ef1c47ea59dfa8721b449420a24919d

**Comment by apurvis** [comment]
@joshuawscott i opened a PR to replace the specs on @infinite-monkeys branch with webmock/VCR - https://github.com/33Across/appnexusapi/pull/1

maybe wait until after that's merged to merge this branch and then cut 1.0?  i think that would be a good path.

**Comment by infinite-monkeys** [comment]
@joshuawscott The tests we had talk directly to Appnexus endpoints (to verify functionality on API updates).  I'm wondering if the credentials you have don't have access to the [advertiser service](https://wiki.appnexus.com/display/api/Advertiser+Service)?

```{"error_id"=>"SYNTAX", "error"=>"Invalid path, unknown service [advertiser]", "error_description"=>nil, "service"=>nil, "method"=>"POST", "error_code"=>nil}```

**Comment by joshuawscott** [comment]
@infinite-monkeys it's very possible, we are not an advertiser or publisher, we are a DSP.

**Comment by infinite-monkeys** [comment]
Oh, well this'll be fun.  All the more reason for @apurvis 's changes to not have the primary tests actually talk to the APIs ... but this does complicate updating those, as well as test suites that do actually want to hit live endpoints.

**Comment by apurvis** [comment]
just crossposting from https://github.com/33Across/appnexusapi/pull/2

> The tests are actually 100% functionally exactly the same, they just run against recorded responses instead of against appnexus's sandbox.

> You can, however, run them against production just by deleting all the VCR files (rm spec/fixtures/vcr/*.yml) and doing what you did before - then they will run against the sandbox again.

**Comment by apurvis** [comment]
> All the more reason for @apurvis 's changes to not have the primary tests actually talk to the APIs

yeah that's one of the upsides; the other majory upside is that you don't need to provide any login or password just to run specs, which is a bit of a smell IMHO.

**Comment by apurvis** [comment]
actually does that issue - access - account for the fact that i could not get the placement service spec to pass?  I added [a `pending` directive](https://github.com/simplifi/appnexusapi/blob/master/spec/integration/placement_spec.rb#L10) so the suite doesn't fail but maybe someone who actually has that level of access needs to go record a valid VCR cassette.

**Comment by apurvis** [comment]
(i thought it was just a missing environment variable or undocumented configuration because there was no `default_site_id` configured anywhere and the spec references that)

**Comment by joshuawscott** [comment]
I'll look into that; I'm not actually on the team that uses this library, so I'm not clear on the details of how all the access works.

**Comment by infinite-monkeys** [comment]
That may be the case.

Did you configure an `APPNEXUS_ADVERTISER_ID` in your .env?

I'm aware that not all accounts have access to create advertisers in their network, and it's possible you may not have access to your `default_site_id` in some cases as well.  (Note the [docs](https://wiki.appnexus.com/display/api/Publisher+Service) mention you can have a publisher with no default site id -- `default_placement=false`)

If you are creating a new advertiser, I suspect that spec should have worked.

I had some other stuff come up this weekend, so I didn't get a chance to play with vcr.

**Comment by apurvis** [comment]
just to be clear, the only spec _we_ weren't able to get to pass was the [placement spec](https://github.com/simplifi/appnexusapi/blob/master/spec/integration/placement_spec.rb); @joshuawscott's story may be different.

if you have a chance a good thing might be to try to get that spec to pass and record a VCR cassette for it; you'll see how VCR works and fix a failing spec.  but it's not urgent or anything.

**Pull request merged**
