### PR TITLE
More endpoints, more tests, more things + webmock vcr specs

### PR DESCRIPTION
**Pull request by apurvis**
This PR is basically  3 things rolled into one
1. https://github.com/simplifi/appnexusapi/pull/13 by @infinite-monkeys 
1. a few more fixes on @infinite-monkeys `V0.1.2 33x` branch that aren't on his `upstream_merge` branch (specifically looks like a retry fix)
1. my PR that replaces the specs with VCR/webmock specs (https://github.com/33Across/appnexusapi/pull/1)

@joshuawscott you can merge them in steps or or just merge this one, though it would be good to have buy in from @infinite-monkeys.

once this (or those two) PRs are merged, let's cut 1.0.

### CODE REVIEW

**Comment by joshuawscott** [comment]
I'm still getting a failure:
```
Failures:

  1) AppNexus Advertiser supports a get operation
     Failure/Error:
       expect do
         advertiser_service.get(num_elements: 1)
       end.to_not raise_error

       expected no Exception, got #<RuntimeError: INVALID_LOGIN/the username/password value is not valid> with backtrace:
         # ./lib/appnexusapi/connection.rb:36:in `login'
         # ./lib/appnexusapi/connection.rb:67:in `run_request'
         # ./lib/appnexusapi/connection.rb:47:in `get'
         # ./lib/appnexusapi/service.rb:44:in `get'
         # ./spec/integration/advertiser_spec.rb:12:in `block (3 levels) in <top (required)>'
         # ./spec/integration/advertiser_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/integration/advertiser_spec.rb:11:in `block (2 levels) in <top (required)>'

```

**Comment by apurvis** [comment]
yeah it probably got missed; i'll fix it.

**Comment by apurvis** [comment]
actually @joshuawscott that spec was marked `pending 'writeme, testme, useme'` so it wasn't really "failing"... regardless i have fixed it up now.

**Comment by joshuawscott** [comment]
@apurvis @infinite-monkeys version 1.0.0 pushed to rubygems.

**Comment by apurvis** [comment]
great; thx

**Pull request merged**
