### PR TITLE
Merge several forks' commits; add log level data (FKA siphon) service

### PR DESCRIPTION
**Pull request by apurvis**
I started with the branch that updates Faraday by @hollow and added a few features:

* verbose logging of Faraday requests and responses via the `APPNEXUS_API_DEBUG` environment variable
* added `LogLevelDataService` and `LogLevelDataDownloadService` classes to handle finding new log level data and downloading the files.  There was a several year old attempt to do this on this PR: https://github.com/simplifi/appnexusapi/pull/3 back when it was still called `Siphon`

### CODE REVIEW

**Comment by hollow** [comment]
:+1:

**Comment by joshuawscott** [comment]
@apurvis Thanks for the PR!

We're going to just double check that our current code works with this, and then we should be good to merge. The ones of us who maintain that code are all going to a conference through the end of the week, so it might be early next week before it gets done.

**Comment by apurvis** [comment]
there's no rush at all on our end; take your time.

wish this project had some VCR/webmock specs though!

**Comment by rfroetscher** [comment]
any updates here? are you planning to merge?

**Comment by joshuawscott** [comment]
@apurvis @rfroetscher @hollow Released as v0.0.6. Thanks again!

**Comment by rfroetscher** [comment]
:+1:

**Pull request merged**
